# Generated by Django 3.2.16 on 2023-03-02 02:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_d'),
    ]

    operations = [
        migrations.DeleteModel(
            name='D',
        ),
    ]
