# Generated by Django 3.2.16 on 2023-03-02 04:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20230302_0437'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
    ]
